pipeline {
    agent none
      environment {
        registry = "davout123/pi"
        registryCredential = "docker_creds"
      }
    stages {
        stage('Maven'){
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
        stages {

                 stage('Test') {
                     steps {
                        script {
                            echo 'Deploying....'
                        }
                     }
                 }
            }
        }

         stage('Deploy') {
            agent any
             steps {
                script {
                    def dockerImage = docker.build("my-image:${env.BUILD_ID}")
                    dockerImage.push()
                }
             }
         }

        stage('Remote SSH') {
            agent any
            steps {
                sshagent(['pi_key']) {
                    sh 'ssh -o StrictHostKeyChecking=no pi@192.168.1.12 "./deploy.sh"'
                }
            }
        }




    }
}


